version: '3.6'

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - .:/app
    restart: always
    entrypoint: ["python", "bot.py"]

  client:
    build: .
    env_file: .env
    volumes:
      - .:/app
    restart: always
    entrypoint: ["python", "client.py"]